"""
Mappings for the Logitech F310
"""

AXIS_LEFT_STICK_Y = 1
AXIS_LEFT_STICK_X = 2
AXIS_RIGHT_STICK_X = 3
AXIS_RIGHT_STICK_Y = 4
AXIS_DPAD_X = 5
AXIS_DPAD_Y = 6

BUTTON_X = 1
BUTTON_A = 2
BUTTON_B = 3
BUTTON_Y = 4
BUTTON_LEFT_BUMPER = 5
BUTTON_RIGHT_BUMBER = 6
BUTTON_LEFT_TRIGGER = 7
BUTTON_RIGHT_TRIGGER = 8
BUTTON_BACK = 9
BUTTON_START = 10
BUTTON_LEFT_STICK = 11
BUTTON_RIGHT_STICK = 12
